--5.2 字符串文字中包含引号
--字符串内写单引号，只需要把一个单引号换成两个单引号即可
SELECT 'G''DAY MATE' QMARKS
  FROM DUAL
UNION ALL
SELECT 'BEAVERS''TEETH'
  FROM DUAL
UNION ALL
SELECT '''' FROM DUAL;

--使用Q-QUOTE界定符
--Q-QUOTE界定符可以是除了TAB、空格、回车以外的任何单字节或多字节字符
SELECT Q'[G'DAY MATE]' QMARKS
  FROM DUAL
UNION ALL
SELECT Q'[BEAVERS'TEETH]'
  FROM DUAL
UNION ALL
SELECT Q'[']' FROM DUAL;
