--5.5 将字符和数字数据分离
DROP TABLE DEPT2 PURGE;  --删除表格并清空回收站

CREATE TABLE DEPT2 AS SELECT DNAME || DEPTNO AS DATA FROM DEPT;

SELECT DATA FROM DEPT2;

SELECT REGEXP_REPLACE(DATA, '[0-9]', '') DNAME,
       REGEXP_REPLACE(DATA, '[^0-9]', '') DEPTNO
  FROM DEPT2;
