--5.8 按字符串的数值排序
CREATE OR REPLACE VIEW V AS 
SELECT DNAME || ' ' || DEPTNO || LOC AS DATA FROM DEPT ORDER BY DNAME;

SELECT * FROM V;

SELECT DATA, TO_NUMBER(REGEXP_REPLACE(DATA, '[^0-9]', '')) AS DEPTNO
  FROM V
 ORDER BY 2;
 
SELECT DATA,
       TO_NUMBER(TRANSLATE(DATA, '0123456789' || DATA, '0123456789')) AS DEPTNO
  FROM V
 ORDER BY 2;
