--6.5 返回各部门工资排名前三位的员工
SELECT *
  FROM (SELECT DEPTNO,
               EMPNO,
               SAL,
               ROW_NUMBER() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS ROW_NUMBER,
               RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS RANK,
               DENSE_RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS DENSE_RANK
          FROM EMP
         ORDER BY 1, 3 DESC)
 WHERE DENSE_RANK <= 3;
